### ISSUE TITLE
init pipe-connector uses a lot of CPU when WSL exited

### ISSUE THREAD

**Issue by dracos** [rupor-github/ssh-agent-wsl#11] opened 2019-06-10 16:31 UTC
I have it all installed and set up and working nicely, thanks! The only issue appears to be that upon exiting WSL, the pipe-connector init process (created the first time I ssh inside WSL) sticks around and starts using up a lot of CPU. I can kill in the Windows Task Manager, but not ideal.
![image](https://user-images.githubusercontent.com/154364/59210441-804e7180-8ba5-11e9-9fb7-5a6f1e207824.png)

**Comment by rupor-github** [comment] 2019-06-10 17:27
I am not sure this is related to pipe-connector, or even ssh-agent-wsl. I was able to find init with high CPU on my box once, however after killing it I cannot reproduce "high CPU" usage... Will try to watch and see - may be we can find out what causes this.

**Comment by dracos** [comment] 2019-06-10 17:28
The init with high CPU is listed in `ps` as `/init /mnt/c/Users/Matthew/bin/pipe-connector.exe 00000000`. I assume if it's not being killed at exit, it gets confused? It happens every single time for me, so if I can help debug it somehow, happy to.

**Comment by rupor-github** [comment] 2019-06-10 17:37
I do not kill it on exit, the only thing I do in my .zshrc is `eval $(ssh-agent-wsl -s -r -H ${HOME}/winhome/.wsl/pipe-connector.exe)`. Judging by the fact that I had it once - it should be reproducible even on my box, I am not sure under what conditions and I do not know what could cause  spinning...

**Comment by rupor-github** [comment] 2019-06-10 18:26
@dracos - Please, try latest release: https://github.com/rupor-github/ssh-agent-wsl/releases/tag/2.3 and see if it helps.

**Comment by dracos** [comment] 2019-06-11 08:30
Hiya - yes, if I run that with the new `-b` option, there's no runaway CPU after the last process is exited, thanks! (Don't really understand what that option does, but guess it doesn't matter :) )

**Comment by rupor-github** [comment] 2019-06-11 10:48
I think in your case it should exit properly even without `-b`, but if it works - it works

**Comment by AnonymousRetard** [comment] 2019-07-24 11:57
I installed this today and it's working nicely. Except that I have this issue as well. I am running version 2.3 of ssh-agent-wsl installed through Scoop.

The problem seems to happen 100% of the time if I do the following sequence of events:
1. Launch Ubuntu bash for Windows (But I also have the exact same issue in a WSL ArchLinux system using ZSH instead of bash)
2. Run "ssh-add -l" (This should launch the pipe-connector.exe process and keep it running)
3. Run "exit"

At this point the window takes 1-2 extra seconds to close than normally and then I have a runaway "init" process using 100% cpu in the task manager. If I launch another bash window and check "htop" it shows me that "pipe-connector.exe" is using 100% CPU.
If I skip step 2 so that pipe-connector.exe never launches the issue does not happen. The issue also doesn't seem to happen every time if i close the window using the mouse with the "X" symbol in the top right corner instead of running "exit".

If I add the "-b" option to .bashrc or .zshrc then this problem does not occurr. On the other hand with that setup it launches an extra ssh-agent-wsl each time I open a bash/zsh window that never dies. Eventually they have to be closed manually or I will have hundreds of those processes after opening/closing the terminal window enough times.

**Comment by rupor-github** [comment] 2019-07-24 12:35
1-2 second delay is due to some mechanics in the code which replaces proper Unix "daemonization" of ssh-agent-wsl process on WSL - it is mentioned in readme. I have seen problem you are describing, unfortunately the only way I was able to avoid this was to be extra careful when starting and killing ssh-agen-wsl - I was not able to simply repeat what I do on real Linux. So I count instances of bash and zsh started and my bashrc/zshrc are aware of tmux.

Something like that for bashrc:

```
    if [ ${ISWSL} -eq 1 ]; then

        # lets count instances
        mkdir -p /tmp/wslinst
        tmpinst=$(mktemp /tmp/wslinst/bash.XXXXXXXXX)
        funcname=$(basename ${tmpinst})

        eval "$(cat <<EOF
            function _cleanup_${funcname}() {
                rm -f ${tmpinst}
                ls -1 /tmp/wslinst/ | wc -l | grep -E "^0$"
                if [ $? == 0 ]; then
                    eval \$(${HOME}/winhome/.wsl/ssh-agent-wsl -k)
                fi
            }
EOF
)"
        eval $(${HOME}/winhome/.wsl/ssh-agent-wsl -s -r)
        trap  _cleanup_${funcname} EXIT
    else
        ....
```

and like this for zshrc:

```
        if [ ${ISWSL} -eq 1 ]; then
            plugins=(gitstatus safe-paste)

            # lets count instances
            mkdir -p /tmp/wslinst
            tmpinst=$(mktemp /tmp/wslinst/zsh.XXXXXXXXX)
            funcname=$(basename ${tmpinst})

            function _cleanup_${funcname}() {
                rm -f ${tmpinst}
                ls -1 /tmp/wslinst/ | wc -l | grep -E "^0$"
                if [[ $? == 0 ]]; then
                    eval $(${HOME}/winhome/.wsl/ssh-agent-wsl -k)
                fi
            }
            autoload -Uz add-zsh-hook
            add-zsh-hook zshexit _cleanup_${funcname}

            # connect to Windows own ssh-agent
            eval $(${HOME}/winhome/.wsl/ssh-agent-wsl -s -r)
        else
           ....
```

**Comment by AnonymousRetard** [comment] 2019-07-30 08:24
Hi again! Unfortunately your .bashrc and .zshrc scripts don't seem to do anything for me.
Besides, even if they managed to kill any runaway "pipe-connector.exe" process when I relaunch the terminal it's not really optimal. Because the process starts maxing out one of my CPU cores only when I close the terminal, and it could take time before I notice something is wrong.

Launching a terminal again to kill this runaway process is not really a nice solution. I probably closed the terminal because I was done with it.

It's not the ssh-agent-wsl process that uses a lot of CPU and I don't care that much if I get a lot of those hanging around if they don't consume much resources. It's the pipe-connector.exe process that is maxing a CPU core after I close the terminal.

What does work instead of your script is just adding "killall pipe-connector.exe" to the .bashrc/.zshrc files before I launch another ssh-agent-wsl. That will kill any previous runaway process once I open a new terminal but it's still not a nice fix for this as I said in the beginning.

I have recorded a GIF clearly showing my problem here: https://ibb.co/ZVCSw1K
On my system this is reproducible 100% of the time and it doesn't matter if I use bash or ZSH or WSL Ubuntu or WSL Arch, they all experience the same problem.

Edit: As I said in my previous post, if I add the "-b" option to the ssh-agent-wsl daemon then "pipe-connector.exe" never starts consuming 100% cpu and it doesn't even keep running after I close the terminal either. Instead ssh-agent-wsl keeps running and it launches 1 extra running instance for each terminal window I have opened. But at least those processes don't consume much CPU or RAM at all.

**Comment by rupor-github** [comment] 2019-07-30 09:22
Short of moving the whole machinery out of WSL and providing a simple proper socket from outside (which seems possible after 1809) I doubt I could really improve situation here. However let's start with reproduction info. Could you please describe your environment, like exact Windows/WSL version you are using and how you start bash/zsh (is it CMD? Windows Terminal? wsltty/mintty, etc)?

**Comment by AnonymousRetard** [comment] 2019-07-30 09:47
I am running Windows 10 Pro Version 1903. OS Build 18362.239.

I am launching the "Ubuntu" or "WSL Arch Linux" app directly from the start menu that I have installed through the Windows store to launch these terminals. I'm not sure how to check the version of WSL but I suspect it's version 1?

My WSL does not accept --version or --verbose as arguments, it just prints the help instead. I think WSL 2 is supposed to accept those arguments?

I have installed the Windows Terminal Beta from the store so I tried this scenario in that as well and it experiences exactly the same problem. In my profiles.json the launch command for ubuntu is "wsl.exe -d Ubuntu".

The same problem happens regardless if I do this in a tab in Windows Terminal, or if I launch the "Ubuntu" app directly from the start menu or if I directly run "Windows KEY+R" "wsl.exe -d Ubuntu" or if I first open CMD and then run "wsl.exe -d Ubuntu".

**Comment by rupor-github** [comment] 2019-07-30 10:02
And each started bash does `eval $(ssh-agent-wsl -s -r)`, right?

**Comment by AnonymousRetard** [comment] 2019-07-30 10:33
Yup,

Or, more specifically they do this:

eval $(/mnt/c/Users/alearq/scoop/apps/ssh-agent-wsl/current/ssh-agent-wsl
-s -r) > /dev/null

(I have to specify the full path and I pipe the output to /dev/null so I
don't have to see the text with the PID each time I open a terminal window).

**Comment by rupor-github** [comment] 2019-07-30 17:25
@AnonymousRetard - please, try latest version (2.4)

**Comment by AnonymousRetard** [comment] 2019-08-01 12:09
Today I updated to ssh-agent-wsl 2.4 using scoop and tried this again. Unfortunately I didn't notice any difference and the issue remains: https://imgur.com/a/EwWJLx2

I looked through the code a bit but unfortunately I'm not experienced enough in regular C to be able to spot what the problem could be... I guess it has to be the pipe-connector.exe (master/win32/main.c) - which is based on weasel-pageant?, that goes haywire and starts spinning tightly in the while (1) {} loop inside static void main_loop(const HANDLE output, const HANDLE input).

I have no idea where it's receiving or sending packages at that point though... Unfortunately I have never really debugged C code before either and I can't spend the time right now to learn it.

Anyways, weasel-pageant seems to have an open issue with the same problem: https://github.com/vuori/weasel-pageant/issues/15

So perhaps we can follow the development there and see if they eventually figure out what happens?

Also I found and modified a bash script today which now checks for the presence of "ssh-agent-wsl". 

1. If the monitor script/process itself (pipe-connector-monitor) is already running then it doesn't launch again.
2. If "ssh-agent-wsl" process isn't running then my monitoring process exits.
3. If "ssh-agent-wsl" is running then it checks for the presence and CPU usage of pipe-connector.exe.
4. If the CPU usage of pipe-connector.exe is above 90% then it kills it.
5. After this it sleeps for 2 seconds before looping back to step 2 to continue the polling.

The script doesn't look very pretty but if someone is interested I can post the code.

It's not a pretty solution at all but it solves this problem completely for now by adding one extra line at the bottom of .bashrc:

eval $(/mnt/c/Users/alearq/scoop/apps/ssh-agent-wsl/current/ssh-agent-wsl -s -r) > /dev/null                                                                                                                                                 
**nohup ~/pipe-connector-monitor 2> /dev/null < /dev/null &**

**Comment by rupor-github** [comment] 2019-08-01 12:28
I cannot reproduce this on 2 of my boxes with 2.4 (both are 18362.267) - previously (2.3) I was able to reproduce it easily. Normally I do follow procedure outlined above - start with eval and kill agent when last wsl instance exits. No leftover init processes either. I think it is easier than monitoring and killing run-away connectors.

As for what is happening - I traced connector using OutputDebugString and it seems like it consumes CPU *after* exiting main(), not in our code, so we have no control over this.

IMHO proper way of getting rig of all this would be either to produce our own ssh-agent.exe Windows service which uses AF_ UNIX socket alongside with pipe or providing ssh-agent-wsl.exe service which translates pipe into proper socket on Windows side. Both with unknown security consequences.  May look into that later - but given the road to WSL 2 this may not be long lived. Modifying programs to follow Unix session semantics under WSL seems a bit fragile due to undocumented nature of WSL interop.

I will do one last attempt later to setup Windows debugger again - init process runs with some serious settings on Windows end and so far all my attempts to actually debug it ended with "access denied". Short of that - I do not know what to do.

**Comment by AnonymousRetard** [comment] 2019-08-01 12:36
Strange that we don't see the same issue. On my end it's definately possible to recreate with 100% accuracy...
But thanks for looking into this. For now I will keep running this together with my monitoring script and hope that this issue disappears once WSL 2 comes around.

I tried to create a memory dump for you from Windows of "init" running at 100% but yeah I also get an error message of "Access denied". Probably what happens if you try to attach to the process with a debugger as well :-/.

**Comment by rupor-github** [comment] 2019-08-01 12:42
I could reproduce it if I use 2.3 and issue `ssh-agent-wsl -k` without the delay after it. ssh-agent exits first and WSL is trying to kill pipe connector and it goes into CPU eating loop. If I put `sleep 1` right after `ssh-agent-wsl -k` - it does not. Key here seems to be the idea that connector should exit *before* WSL kills conhost for the session or something is very confused. So I added 1 second delay after `kill` in ssh-agent code in 2.4. If you follow what I do properly trapping exits from shells you should be fine without monitoring. At least I am.

**Comment by rupor-github** [comment] 2019-08-01 14:26
@AnonymousRetard: I stepped through the connector termination process in WinDbg - CPU consumption happens after program exited. I am going to close this issue, current workaround is described above.

**Closed as completed by rupor-github** 2019-08-01 14:26 UTC
Labels: bug, wontfix
