### ISSUE TITLE
agent key RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxx returned incorrect signature type

### ISSUE THREAD

**Issue by jm33-m0** [rupor-github/ssh-agent-wsl#4] opened 2018-09-08 03:02 UTC
ssh-agent works fine, but whenever I log into my server, I got:
`agent key RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx returned incorrect signature type`

**Comment by rupor-github** [comment] 2018-09-08 11:16
Could you please provide a bit more information? Like what Linux distro you run on WSL, and what is the server distro (sshd?) you connect to? May be collecting debug trace with `ssh -vvv`. Brief search on googlle points to bugs in some releases of openssh server: https://bugzilla.redhat.com/show_bug.cgi?id=1332082 or  BitwiseSSH: https://www.ietf.org/mail-archive/web/secsh/current/msg01244.html. I am affraid this may have nothing to do with agent...

**Comment by jm33-m0** [comment] 2018-09-08 13:05
it seems like agent key is signed with sha256 while sha512 is expected
```
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
agent key RSA SHA256:CDZMcjmJOC5GsJMoK21a8n7/MqV3Nbsdvsbehfym5uw returned incorrect signature type
```

**Comment by rupor-github** [comment] 2018-09-08 13:58
Signing keys is not done by `ssh-agent-wsl` - it simply asks windows service `ssh-agent` to provide information and relays it to the requesting program (ssh client). As such this is most likely incompatibility between version of Windows ssh-agent you have and sshd you are trying to connect to - there was a lot work done on "key" part of ssh implementation: https://github.com/PowerShell/openssh-portable. I do not think it could be fixed in my code. Since you provide no information on versions running - I cannot even try to reproduce it, so I have no further info and no possible actions to take.

Meantime you could try something like that and see if will help:
`ssh -o FingerprintHash=sha512 <your server host>`

**Closed as completed** 2018-09-08 13:59 UTC
Labels: wontfix
